controller_list:
  - name: fake_open_arm_controller
    type: $(arg execution_type)
    joints:
      - joint1
      - joint2
      - joint3
      - joint4
  - name: fake_open_hand_controller
    type: $(arg execution_type)
    joints:
      - gripper
initial:  # Define initial robot poses.
  - group: open_arm
    pose: home